### ISSUE TITLE
Webinar and podcast links not working

### ISSUE THREAD

**Issue by delenamalan** [globaldatanet/aws-firewall-factory#352]
Hi team,

The podcast link in the README (https://github.com/richarvey/aws-community-radio/issues/3) links to a deleted Github issue.

And I've registered for the linked webinar (https://globaldatanet.com/webinars/managing-aws-web-application-firewalls-at-scale), but I haven't received a link to watch it yet. Is it available anywhere else to watch?

**Comment by daknhh** [comment]
Hey, thanks for letting us know. 

I will remove the podcast link.

Here is the link to the recording: https://drive.google.com/file/d/1JCbCjxHwtXWtm_d8-HgYzBfBXkaopniP/view?usp=drive_link

and also the slides: https://docs.google.com/presentation/d/1jE_DmNk0cCc1XM8eBYPM2za0pzGyg9Lv/edit?usp=drive_link&ouid=115444461121738087344&rtpof=true&sd=true
