### ISSUE TITLE
Fixes on the CloudWatch dashboard

### ISSUE THREAD

**Issue by vboufleur** [globaldatanet/aws-firewall-factory#380]
**Describe the bug**
Since the new major version there's some problems with the CloudWatch dashboard generated by aws-firewall-factory.

The name is coming as `undefined` on the deploy logs via `task deploy`:
![image](https://github.com/globaldatanet/aws-firewall-factory/assets/16310611/a9d8d75a-d93a-440b-9fa5-a53dff016eec)

The data aren't being shown on the dashboard:
![image](https://github.com/globaldatanet/aws-firewall-factory/assets/16310611/29e45e34-7da0-4a06-b67e-7e7bd668e122)

**How to reproduce it**
Deploy aws-firewall-factory on a account with active ALLOW and BLOCK data and see the dashboards not being updated.

**Expected behaviour**
A dash name that doesn't has `undefined` in it and live data on the CloudWatch dashboard of the WAF rules working.

**Please fill in the following information about the solution:**.
- Version: 4.2.3
- Region: sa-east-1
- Has the solution been modified from the version posted to this repository? **Yes**
- If yes, are the changes available on GitHub? **No**

**Comment by daknhh** [comment]
Hey thanks for notifying about this bug I will try to already implement the fix in the next release.
