### ISSUE TITLE
Implement support for CloudWatch Log and logging directly to S3 bucket

### ISSUE THREAD

**Issue by daknhh** [globaldatanet/aws-firewall-factory#41]

**Comment by daknhh** [comment]
https://aws.amazon.com/about-aws/whats-new/2021/12/awf-waf-cloudwatch-log-s3-bucket/

**Comment by vboufleur** [comment]
@daknhh I can work on this, my organization needs it to better parse the firewall logs. I was thinking about using AWS Athena to parse the logs on the S3 bucket, but I'm used to CloudWatch LogInsights, I prefer parsing the logs there.

I was thinking of modifying the repo to direct all logs to a centralized log group, created by the repo on the FMS manager account.

Do you have any tips or directions to help me develop this feature? I'm thinking about adding a prop to the config, under `General`, that when specified all logs will be redirect to the ARN of the centralized log group, which'll be specified there. If you could please share some directions for this implementation it'll help me a lot.

**Comment by vboufleur** [comment]
I'm thinking about just adding a option to enable Firehose to log to a CloudWatch Log Group, so that we can have firewall logs on both a S3 bucket and a Cloudwatch Log Group. It can be enabled by setting this property on `CFNDeliveryStream.extendedS3DestinationConfiguration`: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_kinesisfirehose.CfnDeliveryStream.CloudWatchLoggingOptionsProperty.html

**Comment by vboufleur** [comment]
Yeah, it can't be done right now. I tried pointing the FMS logs to a CloudWatch Log Group and got this error:

```
11:25:12 AM | UPDATE_FAILED        | AWS::FMS::Policy           | CfnPolicy
Resource handler returned message: "Only Amazon Kinesis Data Firehose and Amazon S3 Log destinations are supported (Service: Fms, Status Code: 400, Request ID: 64cbc909-2f62-4a5d-aa3d-25c1ab4709a1)" (RequestToken: 65fad254-50c4-239c-6807-078900343d8c
, HandlerErrorCode: InvalidRequest)
```

We'll have to wait for AWS to implement this, if they plan to. I suggest to close this issue.

**Comment by daknhh** [comment]
I think only cfn is not supported yet, because s3 logging just launched few weeks ago: https://aws.amazon.com/about-aws/whats-new/2023/04/aws-firewall-manager-waf-features/

**Comment by vboufleur** [comment]
Oh, in that case we should just wait for a bit, they'll probably add the changes to CNF too.
