### ISSUE TITLE
Missing `example.json` file

### ISSUE THREAD

**Issue by mmoallemi99** [globaldatanet/aws-firewall-factory#45]
The file mentioned leads to a 404 page. 
https://github.com/globaldatanet/aws-firewall-factory/blob/a4d4f89a3f86b488f05c5c501bd877a7bd035010/README.md?plain=1#L144

**Comment by daknhh** [comment]
Thanks i will fix that in the next release

**Comment by daknhh** [comment]
fixed in https://github.com/globaldatanet/aws-firewall-factory/releases/tag/3.1.0
