### ISSUE TITLE
Task validateconfig fails because of missing /test/config-loader.ts

### ISSUE THREAD

**Issue by stoennies** [globaldatanet/aws-firewall-factory#46]
Why I try to run valiedateconfig it fails beacuas of the missing config-loader.ts

**Comment by daknhh** [comment]
Fixed here will be official released soon: https://github.com/globaldatanet/aws-firewall-factory/commit/b9755e87bb74b261e73ad95d3274424d41c7b4d2

**Comment by daknhh** [comment]
fixed in https://github.com/globaldatanet/aws-firewall-factory/releases/tag/3.1.0
