### ISSUE TITLE
Error while bootstraping CDK in app folder: "ENOENT: no such file or directory, open 'cdk.out/manifest.json'"

### ISSUE THREAD

**Issue by vboufleur** [globaldatanet/aws-firewall-factory#51]
Hi,

I tried the simplest way for bootstraping the CDK in my AWS env, but it is failing due to not finding the `cdk.out/manifest.json` file:

![Screenshot_20230418_104801](https://user-images.githubusercontent.com/16310611/232797844-7f0734db-9a2f-4704-abd4-02a196505fba.png)

I'm going to have to bootstrap the CDK manually with a CloudFormation template, but it is full of parameters that I don't understand fully, so I'm going to have to experiment and see if it works for this repo.

What do you think about adding the `cdk.out/manifest.json`  file to the repo? It would make the bootstraping process way easier for those of us that aren't that experienced in working with AWS.

Below are the parameters for bootstraping CDK with a CloudFormation file. I'll try it out, but if you could help me with this, for example, by saying which minimum permissions and parameters are strictly required, it'll help me a lot.

![Screenshot_20230418_105402](https://user-images.githubusercontent.com/16310611/232799388-e0012dff-2b91-4e80-9924-d2cfef7870cf.png)
![Screenshot_20230418_105424](https://user-images.githubusercontent.com/16310611/232799474-63098bdd-3249-48d9-8b02-1a7bba0e47cd.png)

**Comment by daknhh** [comment]
Hi @vboufleur i think the easiest is to follow the official documentation to bootstrap your account with a custom template: https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html -

**Comment by vboufleur** [comment]
It worked! If anyone is interested in the permissions I gave to the CDK bootstrap CloudFormation stack, I've used this stack file: `cdk bootstrap --show-template > bootstrap-cdk.yml` and I've put the default parameters on it, except `CloudFormationExecutionPolicies`, and I gave it these permissions for being able to deploy aws-firewall-factory:
```
arn:aws:iam::aws:policy/AWSWAFFullAccess,arn:aws:iam::aws:policy/CloudWatchFullAccess,arn:aws:iam::aws:policy/AmazonS3FullAccess,arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess,arn:aws:iam::aws:policy/CloudFrontFullAccess,arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator,arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
```

@daknhh What do you think about adding this to the docs? It could save some time for newcomers as I've spent a long time figuring this out.

**Comment by vboufleur** [comment]
I think I've added too much permissions for it, for example `AmazonAPIGatewayAdministrator` is not needed right? Please let me know to adjust the permissions to the minimum required. Thanks!

**Comment by daknhh** [comment]
Needed:
arn:aws:iam::aws:policy/AWSWAFFullAccess ->FMS and WAF
arn:aws:iam::aws:policy/CloudWatchFullAccess -> Dashboarding
arn:aws:iam::aws:policy/AmazonS3FullAccess
arn:aws:iam::aws:policy/AmazonKinesisFirehoseFullAccess -> KinesisStream

Not needed:
arn:aws:iam::aws:policy/CloudFrontFullAccess
arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
