### ISSUE TITLE
What does "overrideCustomerWebACLAssociation" means?

### ISSUE THREAD

**Issue by vboufleur** [globaldatanet/aws-firewall-factory#58]
Hi!

Just a quick question, I've seen that in the [firewall-stack.ts](https://github.com/globaldatanet/aws-firewall-factory/blob/master/lib/firewall-stack.ts#L142) file the prop `overrideCustomerWebACLAssociation` is set to `true`. I've searched the [SecurityServicePolicyData](https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_SecurityServicePolicyData.html) docs but I've found no explanation about it there.

What exactly does it mean? What happens when it's set to true? I'm asking to check how it'll affect the WAF rules in my accounts. If I see I need it to be set to false I'll send you a PR that adds a option to parametrize this value.

Thanks!

**Comment by vboufleur** [comment]
I've got an answer from a AWS employee, he said this: `When this flag is enabled sometime after policy creation, the internal policy version will increase, forcing a re-evaluation of config rules and remediation workflow`.

I'll close this issue as it seems to be a good idea to leave that prop turned on.

**Comment by daknhh** [comment]
yes- i also just saw that
